version: '3'
services:
  api:
    build: ./api/
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - ./api/.env
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - api