version: '3'
services:
  api:
    build: ./api/
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - ./api/.env
    ports:
      - 8000:8000
    networks:
      - my_network

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - api
    networks:
      - my_network
      
networks:
  my_network:
    driver: bridge